### ISSUE TITLE
No report exists for key...

### ISSUE THREAD

**Issue by dale-wahl** [eshaan7/Flask-Shell2HTTP#24]
I am currently moving a Flask app to Gunicorn and am having an issue where I cannot ever retrieve a report even though it appears that the command will eventually be successfully run. I will send a post to an API endpoint and will receive a successful response that includes the key and `result_url`, but when I make a get request to that url, I only receive the "No report exists for key..." response. At first I thought it might be a delay, but even with repeated get requests I am not able to receive reports. 

I have been looking through your documentation to get a better idea of how to access reports and understand how long before they expire/disappear. I had noticed previously that if I keep making a request for a specific key, it will eventually return `No report exists for key` even if one had previously existed. I am wondering if you have run into similar issues and if you could point me in the right direction to try to track down these reports or log them somewhere more permanent. I also tried playing with the Executor a bit, but am not entirely sure where to start with that.

Thank you for the help.

**Comment by eshaan7** [comment]
Inactive.

**Comment by dale-wahl** [comment]
Hey eshaan7, sorry for the super long delay. I was quite distracted by another project and unable to come back to this until now.

I wanted to thank you for the logging info; it was quite easy to set up. I had much more trouble getting the logging for Gunicorn up and running (which was effecting your logging). Once I did, I figured out that the issue has to do with having multiple Gunicorn workers handling requests. The report only exists for the same worker that handled the original request. I am not sure how to solve it yet, but there you have it. Just did not want to leave you hanging.

Version information you requested:
Python 3.7.11
```
Flask==2.0.2
Flask-Executor==0.9.4
Flask-Shell2HTTP==1.8.0  
```

**Comment by eshaan7** [comment]
Thank you for getting back to me. That's a good find. In my case, I never tried using flask-shell2http with multiple gunicorn workers but I can easily see why it messes things up - flask_shell2http and flask_executor both rely on global variables for state management which are of course not shared between different workers.

For now I can only suggest 2 solutions:
- Use a single gunicorn worker
- Gunicorn can work with [gevent](http://www.gevent.org/) to create a server that can support multiple clients within a single worker process using coroutines.

**Comment by lingfish** [comment]
> * Use a callback function* to store the result in a _shared_ database/cache that is accessible to all gunicorn workers

This is nice, but is obviously only called after a (long running) future completes; what about when trying to poll for a key/job whilst it's still running?  That too would need to go into Redis, but I can't figure a clean way to do this, when using another route to check Redis/the job.



> [multiprocessing.shared_memory](https://docs.python.org/3/library/multiprocessing.shared_memory.html) might work too for central sharable storage.

This got me excited, and then I noticed it's >= Python 3.8, and the server I have to use isn't :(
