### ISSUE TITLE
A way to get binary output

### ISSUE THREAD

**Issue by pink-red** [eshaan7/Flask-Shell2HTTP#44]
First of all, thank you for this project! It was very easy to set up a couple of endpoints.

Now, I am trying to create another endpoint for a command which returns binary output and I'm getting an error:

```
"'utf-8' codec can't decode byte 0xff in position 0: invalid start byte"
```

Is there a way to configure an endpoint to return binary data, for example, in base64?

**Comment by eshaan7** [comment]
> Is there a way to configure an endpoint to return binary data, for example, in base64?

You could try the unix pipe `|` your command to `base64`. For example, `echo "Hello" | base64`. Might need to put your command in a custom script (`.sh`/`.py`/etc) to use pipes though (refer to [this](https://github.com/eshaan7/Flask-Shell2HTTP/blob/master/examples/run_script.py) example).

**Comment by pink-red** [comment]
> You could try the unix pipe `|` your command to `base64`.

Thank you for your suggestion. I ended up creating this wrapper script:
```sh
#!/bin/sh
<the-command> "$@" | base64 --wrap 0
```
and it's called like this:
```python
shell2http.register_command(endpoint="some-enpoint", command_name="./script.sh")
```

Works like a charm!
