### ISSUE TITLE
Adding your own route while using shell2http

### ISSUE THREAD

**Issue by m0bi5** [Eshaan7/Flask-Shell2HTTP#6]
Hey, 

I am currently trying to use a vanilla flask route along with routes defined by shell2http, however, when I access the vanilla flask route, I get a 404. Any idea on how I can do this?

**Comment by Eshaan7** [comment]
Hi. Could you share the code or error logs ? I have used flask-shell2http with vanilla flask routes and it does work fine so it's probably some trivial bug.

**Comment by m0bi5** [comment]
Yes, my bad I was missing a @ before the definition of my vanilla flask route, very trivial mistake. Amazing library btw, would love to contribute!
