### ISSUE TITLE
Generation of result key

### ISSUE THREAD

**Issue by m0bi5** [Eshaan7/Flask-Shell2HTTP#8]
I ran a few tests for an API I built to run a certain command line program, however I noticed that the keys returned are always for a given route, no matter what the parameters are, is this a feature?

**Comment by Eshaan7** [comment]
The route would be same but the key will be different each time. Sometimes
the key can be same if you call the API with same parameters multiple times
within a few seconds.

**Comment by Eshaan7** [comment]
You may reach me at https://twitter.com/mask0fmydisguis or t.me/maskofmydisguise for better support and faster resolution.
